export const stockOptions = [
  { value: "ACB", label: "Ngân hàng Thương mại Cổ phần Á Châu" },
  { value: "BCM", label: "Bamboo Capital" },
  {
    value: "BID",
    label: "Ngân hàng TMCP Đầu tư & Phát triển Việt Nam (BIDV)",
  },
  {
    value: "CTG",
    label: "Ngân hàng TMCP Công Thương Việt Nam (VietinBank)",
  },
  { value: "DGC", label: "Hóa chất Đức Giang" },
  { value: "FPT", label: "FPT Corporation" },
  { value: "GAS", label: "Tổng công ty Khí Việt Nam (PV Gas)" },
  { value: "GVR", label: "Tập đoàn Cao su Việt Nam" },
  { value: "HDB", label: "Ngân hàng TMCP Phát triển TP. Hồ Chí Minh" },
  { value: "HPG", label: "Tập đoàn Hòa Phát" },
  { value: "LPB", label: "Ngân hàng TMCP Bưu điện Liên Việt" },
  { value: "MBB", label: "Ngân hàng TMCP Quân Đội" },
  { value: "MSN", label: "Tập đoàn Masan" },
  { value: "MWG", label: "Thế Giới Di Động" },
  { value: "PLX", label: "Tập đoàn Xăng dầu Việt Nam (Petrolimex)" },
  { value: "SAB", label: "Sabeco (Bia Sài Gòn)" },
  { value: "SHB", label: "Ngân hàng TMCP Sài Hà Nội" },
  { value: "SSB", label: "Ngân hàng TMCP Đông Nam Á" },
  { value: "SSI", label: "Công ty Cổ phần Chứng khoán SSI" },
  {
    value: "STB",
    label: "Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)",
  },
  {
    value: "TCB",
    label: "Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)",
  },
  { value: "TPB", label: "Ngân hàng TMCP Tiên Phong" },
  {
    value: "VCB",
    label: "Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)",
  },
  { value: "VHM", label: "Vinhomes" },
  { value: "VIB", label: "Ngân hàng TMCP Quốc tế Việt Nam" },
  { value: "VIC", label: "Tập đoàn Vingroup" },
  { value: "VJC", label: "Hãng hàng không Vietjet" },
  { value: "VNM", label: "Vinamilk" },
  {
    value: "VPB",
    label: "Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)",
  },
  { value: "VRE", label: "Công ty Cổ phần Vincom Retail" },
];
